github, actions: Add junit report
Signed-off-by: Enrique Llorente <ellorent@redhat.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,9 @@ on:
   pull_request:
    types: [opened, synchronize, reopened]
 
+permissions:
+  checks: write
+
 jobs:
   rust_lint:
     strategy:
@@ -157,7 +160,11 @@ jobs:
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         run: sudo .github/workflows/run_test.sh ${{ matrix.job_type }}
-
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'junit*.xml'
       - name: Set artifacts permissions
         if: ${{ failure() }}
         run: sudo chmod 777 test_artifacts/*
